export const usersData = [
  {
    id: 1,
    name: "John Wick",
    position: "Frontend",
    phone: "+12345678901",
    email: "john@gmail.com",
    photo: "../public/no-photo.png",
  },
  {
    id: 2,
    name: "Dr. Gregory House",
    position: "Doctor",
    phone: "+12345678901",
    email: "greghouse@gmail.com",
    photo: "../public/no-photo.png",
  },
  {
    id: 3,
    name: "Sherlock Holmes",
    position: "Detective",
    phone: "+12345678901",
    email: "sherlock@gmail.com",
    photo: "../public/no-photo.png",
  },
  {
    id: 4,
    name: "Eliott Alderson",
    position: "Hacker",
    phone: "+12345678901",
    email: "eliott@gmail.com",
    photo: "../public/no-photo.png",
  },
  {
    id: 5,
    name: "Bruce Wayne",
    position: "Batman",
    phone: "+12345678901",
    email: "john@gmail.com",
    photo: "../public/no-photo.png",
  },
  {
    id: 6,
    name: "Tony Stark",
    position: "Iron Man",
    phone: "+12345678901",
    email: "stark@gmail.com",
    photo: "../public/no-photo.png",
  },
  {
    id: 7,
    name: "Ada Lovelace",
    position: "Programmer",
    phone: "+12345678901",
    email: "lovelace@gmail.com",
    photo: "../public/no-photo.png",
  },
  {
    id: 8,
    name: "Marie Curie",
    position: "Radiologist",
    phone: "+12345678901",
    email: "curie@gmail.com",
    photo: "../public/no-photo.png",
  },
  {
    id: 9,
    name: "Alan Turing",
    position: "Mathematician",
    phone: "+12345678901",
    email: "turing@gmail.com",
    photo: "../public/no-photo.png",
  },
];
